language: go

go:
  - 1.x

service:
  - docker

sudo: required

jobs:
  include:
    - stage: Check headers
      script: make check-headers
    - stage: Check go files
      script: make check-code
    - stage: Compile
      script: make compile
    - stage: CI
      script: make ci
      before_install:
        - docker build -t eg_sshd test/ssh
        - docker run --rm -p 6666:22 -d --name test_sshd eg_sshd
    - stage: Integration
      before_install:
        - bash ./scripts/e2e.sh

